import React, { useState } from 'react';
import { BookOpen, Search, ShieldCheck, Filter, ExternalLink, Layers, CheckCircle2, AlertTriangle, Shield } from 'lucide-react';

export const RuleLibrary: React.FC = () => {
  const [search, setSearch] = useState('');
  const [selectedFramework, setSelectedFramework] = useState('all');

  const rules = [
    { id: 'SEC-INJ-001', name: 'Direct Prompt Injection Defense', framework: 'OWASP ASI-01', severity: 'CRITICAL', desc: 'Verifies system prompt boundary isolation against override jailbreak attempts.' },
    { id: 'SEC-PII-001', name: 'PII & Confidential Data Leakage Redaction', framework: 'DPDP / GDPR', severity: 'CRITICAL', desc: 'Prevents output emission of SSN, credit cards, banking info, and private credentials.' },
    { id: 'ARCH-HITL-001', name: 'Human-In-The-Loop Execution Gating', framework: 'EU AI Act Art. 14', severity: 'HIGH', desc: 'Enforces human authorization approval gates before destructive tool executions.' },
    { id: 'REL-LOOP-001', name: 'Runaway Agent Iteration & Context Budget Cap', framework: 'NIST AI RMF 1.0', severity: 'HIGH', desc: 'Restricts reasoning step recursion and enforces context token ceilings.' },
    { id: 'ADV-CHAIN-001', name: 'Multi-Step Toolchain Poisoning Resistance', framework: 'MITRE ATLAS', severity: 'CRITICAL', desc: 'Validates state isolation between sequential tool calls to prevent privilege escalation.' },
    { id: 'MCP-SQUAT-001', name: 'Model Context Protocol (MCP) Tool Squatting', framework: 'OWASP ASI-05', severity: 'HIGH', desc: 'Protects against rogue tool registration with duplicate namespace identities.' },
    { id: 'VOICE-ASR-001', name: 'Audio Stream Injection & Safety Filter', framework: 'CertifyAI v7+', severity: 'MEDIUM', desc: 'Evaluates acoustic adversarial injections in live speech-to-text processing pipelines.' },
    { id: 'DATA-SQL-001', name: 'Data Analysis SQL Query Boundary Validation', framework: 'OWASP Top 10', severity: 'CRITICAL', desc: 'Detects unsafe DROP, ALTER, or unparameterized queries generated by data agents.' }
  ];

  const filtered = rules.filter(r => {
    const matchQ = r.name.toLowerCase().includes(search.toLowerCase()) || r.id.toLowerCase().includes(search.toLowerCase()) || r.desc.toLowerCase().includes(search.toLowerCase());
    const matchF = selectedFramework === 'all' || r.framework.includes(selectedFramework);
    return matchQ && matchF;
  });

  return (
    <div className="user-runner-container">
      <div className="runner-header-banner">
        <div className="runner-header-left">
          <div className="runner-icon-cube">
            <BookOpen size={24} />
          </div>
          <div className="runner-title-group">
            <h1 className="runner-title">Compliance Rule & Standards Library</h1>
            <p className="runner-desc">
              Comprehensive registry of 128 safety, security, and regulatory rules mapped to OWASP, NIST, EU AI Act, and DPDP.
            </p>
          </div>
        </div>
      </div>

      <div className="admin-filter-bar" style={{ marginTop: '16px' }}>
        <div className="search-input-box">
          <Search size={16} />
          <input
            type="text"
            placeholder="Search rules by ID, description, or vulnerability pattern..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>

        <div className="filter-dropdowns">
          <div className="filter-item">
            <span className="filter-label">Framework:</span>
            <select value={selectedFramework} onChange={(e) => setSelectedFramework(e.target.value)}>
              <option value="all">All Frameworks (128 rules)</option>
              <option value="OWASP">OWASP Top 10 for Agents</option>
              <option value="NIST">NIST AI RMF 1.0</option>
              <option value="EU AI">EU AI Act (High-Risk AI)</option>
              <option value="DPDP">India DPDP Act (2023)</option>
              <option value="MITRE">MITRE ATLAS</option>
            </select>
          </div>
        </div>
      </div>

      <div className="admin-table-wrapper">
        <table className="admin-table">
          <thead>
            <tr>
              <th>Rule ID</th>
              <th>Rule Title</th>
              <th>Standard Mapping</th>
              <th>Severity Level</th>
              <th>Check Description</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map(r => (
              <tr key={r.id} className="table-row-hover">
                <td><span className="agent-id-tag bold" style={{ color: '#38bdf8' }}>{r.id}</span></td>
                <td><strong style={{ fontSize: '13.5px' }}>{r.name}</strong></td>
                <td><span className="mode-badge certify">{r.framework}</span></td>
                <td>
                  <span className={`finding-pill ${r.severity === 'CRITICAL' ? 'critical' : 'warning'}`}>
                    {r.severity}
                  </span>
                </td>
                <td style={{ color: 'var(--text-secondary)', fontSize: '12.5px' }}>{r.desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
